AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

  Exclude:
    - "_benchmark/**/*"
    - "ruby/testdata/example/vendor/**/*"

    # ref. https://github.com/rubocop/rubocop/blob/v1.66.1/config/default.yml
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Gemspec/RequireMFA:
  Exclude:
    - ruby/testdata/example/example.gemspec

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/SpaceAroundOperators:
  Exclude:
    # Suppress line breaks in spec files (e.g `it { should xxxx }`, `its(:method) { should xxxx }` )
    - "**/*_spec.rb"

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - "**/*_spec.rb" # for rspec-parameterized

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "**/*_spec.rb"

Metrics/ClassLength:
  Exclude:
    - "**/*_test.rb"

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/MethodLength:
  Max: 28

Metrics/PerceivedComplexity:
  Max: 11

Style/Documentation:
  Exclude:
    - "**/*_test.rb"

Style/FetchEnvVar:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
