AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/SpaceAroundOperators:
  Exclude:
    # Suppress line breaks in spec files (e.g `it { should xxxx }`, `its(:method) { should xxxx }` )
    - "**/*_spec.rb"

Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - "**/*_spec.rb" # for rspec-parameterized

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 21

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
