name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name: ruby-go-gem/ruby_header_parser
      gem-name:  ruby_header_parser
    permissions:
      contents: write
      id-token: write
